# Generated by Django 3.2.18 on 2023-09-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customersection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ADDRESS_MASTER',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('startdate', models.DateField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customersection.address')),
            ],
            options={
                'db_table': 'COLLEGE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fees', models.FloatField()),
                ('dept', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'STUDENT_MASTER',
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salary', models.FloatField()),
                ('skill', models.CharField(max_length=40)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='customersection.college')),
                ('students', models.ManyToManyField(related_name='professors', to='customersection.Student')),
            ],
            options={
                'db_table': 'PROFESSOR_MASTER',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sfees', models.FloatField()),
                ('author', models.CharField(max_length=40)),
                ('students', models.ManyToManyField(related_name='courses', to='customersection.Student')),
            ],
            options={
                'db_table': 'COURSE_MASTER',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customersection.student'),
        ),
    ]
